### PR TITLE
Reduce bundle size

### PR DESCRIPTION
**Pull request by merceyz**
**Related issues**
Closes https://github.com/iamhosseindhv/notistack/issues/163

**Changes**

- Build ESM version
- Upgrade to babel 7
- Use `core-js@3` 
- Use `clsx` instead of `classnames`
- Add `@babel/plugin-transform-runtime`
- Add `babel-plugin-optimize-clsx`
- Add browserlist (copied from https://github.com/mui-org/material-ui/blob/80aaebc729c91d05db89ce9064effe4824214437/.browserslistrc )
- Use `cross-env` to fix build on Windows

**Result**
Bundled with rollup, excluding externals

|        |                        |
| ------ | ---------------------- |
| Before | 23,9 KB (24 540 bytes) |
| After  | 19,5 KB (20 050 bytes) |

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
Outdated PR. Propbably a new one takes less time than resolving conflicts on this. Thanks for your contribution @merceyz

**Comment by merceyz** [comment]
I would have had to resolve them anyways, so I did, you can re-open the PR :+1:

**Comment by iamhosseindhv** [comment]
Thanks @merceyz appreciate it a lot. Happy to merge.

Can you share the setup you use to measure bundle size? (last time you mentioned rollup) 
I'd like to add the repo, so from now on we can see the effect of each bit of code being added/removed.

**Comment by iamhosseindhv** [comment]
Fixed in https://github.com/iamhosseindhv/notistack/pull/268 using a third party library.

Huge [thanks](https://github.com/iamhosseindhv/notistack/blob/master/CHANGELOG.md#may-15-2020) for your contribution. Would be my pleasure to have you in contributors list, if you could make a PR with a dummy commit.

**Comment by merceyz** [comment]
> Fixed in #268 using a third party library.

Great, less code to maintain!

> Would be my pleasure to have you in contributors list, if you could make a PR with a dummy commit.

Thank you but that's not necessary :+1:

**Pull request closed without merging**
