### PR TITLE
Add preventDuplicate options

### PR DESCRIPTION
**Pull request by VincentLanglet**
Solve https://github.com/iamhosseindhv/notistack/issues/56

I decided to prevent duplicate only if the previous message is always displayed.

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
Thanks for the PR @VincentLanglet. 👍🏼This will be merged in the future. Closing the issue associated with this PR.

**Comment by VincentLanglet** [comment]
@iamhosseindhv Hi !
We'll need to use this feature for our project. 
Do you have an idea of ​​when this will be merged ? Can I help ?

Thanks

**Comment by iamhosseindhv** [comment]
@VincentLanglet That'd be by Monday. Thanks for the patience.

**Comment by iamhosseindhv** [comment]
@VincentLanglet This is live now.

**Comment by VincentLanglet** [comment]
Nice, thanks

**Pull request merged**
