### PR TITLE
Fix for SnackBarProvider cannot be used as JSX Element

### PR DESCRIPTION
**Pull request by german-bortoli**
This might fix the issue ON https://github.com/iamhosseindhv/notistack/issues/485

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
Thanks for opening the PR, I've not been able to reproduce this issue, so can't test whether this PR fixes anything or not.

**Comment by german-bortoli** [comment]
> Thanks for opening the PR, I've not been able to reproduce this issue, so can't test whether this PR fixes anything or not. I can be of more help if you could open an issue with a reproduction example.

Thanks for "Reviewing" this PR, there are other users who has this issue too, could you please try harder to reproduce the warning message ?

**Comment by sridhar-fx** [comment]
I am seeing this error too

**Comment by iamhosseindhv** [comment]
I've reopened the corresponding issue #485 . I'll try to reproduce if and when I find some time, in the meantime I have to rely on the community to make a reproduction.

**Pull request closed without merging**
