### PR TITLE
Fix typing for iconVariant prop in SnackbarProvider (fixes #90)

### LINKED ISSUE #90: SnackbarProvider has incorrect typing for iconVariant
The current definition is
```
iconVariant?: React.ComponentType<SvgIconProps>;
```
which doesn't match the actual prop type defined in the component (.js file):
```
iconVariant: PropTypes.shape({
        /**
         * Icon displayed when variant of a snackbar is set to `success`.
         */
        success: PropTypes.any.isRequired,
        /**
         * Icon displayed when variant of a snackbar is set to `warning`.
         */
        warning: PropTypes.any.isRequired,
        /**
         * Icon displayed when variant of a snackbar is set to `error`.
         */
        error: PropTypes.any.isRequired,
        /**
         * Icon displayed when variant of a snackbar is set to `info`.
         */
        info: PropTypes.any.isRequired,
    }),
```

### PR DESCRIPTION
**Pull request by amakhrov**

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
Thanks for your contribution @amakhrov. ❤️

**Comment by amakhrov** [comment]
@Thanks @iamhosseindhv 
Any plans for publishing a new package version with this fix? :)

**Comment by iamhosseindhv** [comment]
Just published the fix @amakhrov 👍

**Comment by amakhrov** [comment]
Thanks you so much! :)

**Pull request merged**
