### PR TITLE
Prevent racing conditions

### PR DESCRIPTION
**Pull request by Ang-YC**
First, thanks for making this library, I found it very useful 👍

I found that there are some unexpected behaviour of the library if there are more than 2 notifications in the queue, it will cause some racing condition to happen. The comparison before and after the fix can be seen here:

---

### Before
before_fast

### After
after_fast

---

### Before
before_normal

### After
after_normal

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
Thanks for the time you put into this PR @Ang-YC, really appreciate it.

The only thing that needs to be changed (imo) before merging into master, is that:
with this implementation we're eliminating the delay between "dequeueing a snack" and "hiding the oldest snack". For this reason, the new one overlaps with the latest presented snack, which is not visually pleasing. 

Is that something you can fix?

**Comment by Ang-YC** [comment]
Sounds good to me, so it becomes another option `maxWaiting` or just `maxSnack + 1`?

If `maxWaiting` = 3, the max items waiting in the queue will be 3 before pushing it immediately.
If `maxWaiting` = 0, the items waiting in the queue will be pushed immediately.

The default for `maxWaiting` can be 1.

**Comment by iamhosseindhv** [comment]
That's right.

**Comment by Ang-YC** [comment]
@iamhosseindhv Oh my, I didn't realise you have edited the comment as there are no notifications for editing. I will work on it over this week and let you know. Apologise for the late!

**Comment by iamhosseindhv** [comment]
@Ang-YC No problem at all. Thanks for your contribution. `master` has been changed quite a bit since this PR. Might be good to have a look around [changelog](https://github.com/iamhosseindhv/notistack/blob/master/CHANGELOG.md). 👍🏼

**Pull request closed without merging**
