### PR TITLE
Check for item key when a key is provided to prevent duplicates

### PR DESCRIPTION
**Pull request by kriim**
Currently if you have two notification with the same `message` text, but a different `key`, only the `message` is used to prevent duplicates.

When a user defined `key` is provided to `enqueueSnackbar` it makes sense to compare the `key` instead of the `message` to prevent duplicates.

This becomes relevant when you pass a `React.Node` as `message`. Or when you want to replace a Snackbar with a new one, where the message is the same but the actions are different.

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
Thanks for your contribution @kriim .

Documentation website has been updated accordingly. https://iamhosseindhv.com/notistack/demos#prevent-duplicate

**Comment by kriim** [comment]
Wow, thanks, that was quick :). And no problem, I'm glad to help.

How often do you usually publish releases to npm?

**Comment by iamhosseindhv** [comment]
In case of bug fixes I publish immediately. For features I'll publish when it's worth incrementing the version number. In this case changes will be published when #189 gets merged.

**Comment by kriim** [comment]
Sounds good, thanks for the info.

**Pull request merged**
