### PR TITLE
React Hooks API for discussion

### PR DESCRIPTION
**Pull request by IcculusC**
untested, incomplete implementation of React Hooks API for discussion

I was bored and this seems like a logical step in the direction of [#8](https://github.com/iamhosseindhv/notistack/issues/8)

also ran `eslint --fix` to quiet warnings, so maybe a little messy

### CODE REVIEW

**Comment by FredyC** [comment]
@IcculusC Not sure why there are so much of unrelated changes really. I made myself a custom hook in a couple of LOC. Any hooks related PR should contain something like that and nothing more. If you want to eg. update Material library version, it should be done separately.

```ts
import { SnackbarContextNext } from 'notistack/build/SnackbarContext'
import { useContext } from 'react'

export function useSnackBar() {
  const enqueueSnackbar = useContext(SnackbarContextNext)
  return { enqueueSnackbar }
}

```

**Comment by IcculusC** [comment]
@FredyC again, it's just for discussion.  I didn't make this PR with the intention of having it merged.  It's to demonstrate how a full refactor with new Hooks and Context might look.  I was hoping to get a conversation started.

**Comment by FredyC** [comment]
Ok, in that case please change title to something like "Refactor to use React hooks". The term "Hooks API" might be seen as contains public facing API with hooks. 

Either way I think it's way too soon to rewrite whole lib to hooks, but as an experiment it's ok. I just prefer you wouldn't run that autofix, it's really hard to see real changes there.

**Comment by IcculusC** [comment]
@FredyC is this your repository?  There are no contribution guidelines, and honestly I am interested in the opinions of the maintainers.  I wrote this code in preparation for the final Hooks implementation as a reference point of what is needed to modernize `notistack`.  I'll leave the PR as is, and they can do with it what they will.  Thanks.

**Comment by iamhosseindhv** [comment]
Thanks @IcculusC. This can be a starting point for adding Hooks API. However, hooks api is not a priority of of this library at the moment. Any suggestion/discussion is welcome though.

**Comment by FredyC** [comment]
@IcculusC I am not really interested in starting a discussion with your aggressive stance. It was merely a suggestion. Have fun discussing alone ;)

**Comment by haysclark** [comment]
Hooks seems like a good idea for this project if it helps reduce the number of ContextProviders and ContextProducers generated by notistack.  When I look at my React Devtools, this quote comes to mind:

> If you look at a typical React application in React DevTools, you will likely find a “wrapper hell” of components surrounded by layers of providers, consumers, higher-order components, render props, and other abstractions. - [reactjs.org - hooks-intro](https://reactjs.org/docs/hooks-intro.html#motivation)

React-Router has some good discussion on their implementation of hooks, but they decided to release the feature in there next Major version: 5.0.

**Comment by IcculusC** [comment]
> Hooks seems like a good idea for this project if it helps reduce the number of ContextProviders and ContextProducers generated by notistack. When I look at my React Devtools, this quote comes to mind:
> 
> > If you look at a typical React application in React DevTools, you will likely find a “wrapper hell” of components surrounded by layers of providers, consumers, higher-order components, render props, and other abstractions. - [reactjs.org - hooks-intro](https://reactjs.org/docs/hooks-intro.html#motivation)
> 
> React-Router has some good discussion on their implementation of hooks, but they decided to release the feature in there next Major version: 5.0.

I'm looking forward to the day that there are no HOCs.  :joy:

**Comment by VincentLanglet** [comment]
What is the state of this discussion/PR ?
Hooks are officially released

(Plus, there are conflict)

**Comment by iamhosseindhv** [comment]
It might be a good idea to use hooks in a major release, once we completely deprecate `onPresentSnackbar`. (cause that'll eliminate one of the our contexts)

**Comment by iamhosseindhv** [comment]
At least point we're pretty clear we're gonna add hooks to the library. This however will be added in the next major release.

#77 
#79

**Pull request closed without merging**
