### PR TITLE
Pass relevant props to custom content.

### PR DESCRIPTION
**Pull request by HerrPfister**
Fixes issue https://github.com/iamhosseindhv/notistack/issues/361

Passing all props being used by the `SnackbarContent` to the custom content function.

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
I am actively working to bring this feature to life. The solution I'm working on passes a more exhaustive list of props to the custom component. It'll be published as alpha/v2. 

Features:
* Typescript support
* Pass all the options passed to enqueueSnackbar to the custom component, including additional values needed by your custom component, not just the props supported in notistack.
* Process and merge props from SnackbarProvider and enqueueSnackbar and pass them to your custom component.
* Allow defining custom variants:
```jsx
<SnackbarProvider
    Components={{
         reportComplete: MyCustomReportNotification,
    }}
>
</SnackbarProvider>


// ...
enqueueSnackbar('Your report is ready to download', {
   variant: 'reportComplete',
   persist: true,
   allowDownload: true,
})

```

**Comment by nextglabs** [comment]
Any news about this new feature? Do you need any help @iamhosseindhv?

**Comment by liho00** [comment]
I need the variant props in order to customize the success, error icons... How did I pass the variant prop to the content props?
image

**Comment by iamhosseindhv** [comment]
@nextglabs Any news about this new feature? Do you need any help

You can track the progress on https://github.com/iamhosseindhv/notistack/tree/alpha branch.
For a list of breaking changes see https://github.com/iamhosseindhv/notistack/blob/alpha/MIGRATION.md.

I'm in testing phase before publishing an alpha package, so any help regarding that is appreciated.

**Comment by liho00** [comment]
> @nextglabs Any news about this new feature? Do you need any help
> 
> You can track the progress on [alpha](https://github.com/iamhosseindhv/notistack/tree/alpha) branch.
> For a list of breaking changes see [MIGRATION.md](https://github.com/iamhosseindhv/notistack/blob/alpha/MIGRATION.md).
> 
> I'm in testing phase before publishing an alpha package, so any help regarding that is appreciated.

Could you publish the alpha branch to npm? So easier for us to try it out, just like how i tried material ui v5 alpha. 
176930441_470794991015232_5082482804144397900_n

**Comment by liho00** [comment]
> @nextglabs Any news about this new feature? Do you need any help
> 
> You can track the progress on [alpha](https://github.com/iamhosseindhv/notistack/tree/alpha) branch.
> For a list of breaking changes see [MIGRATION.md](https://github.com/iamhosseindhv/notistack/blob/alpha/MIGRATION.md).
> 
> I'm in testing phase before publishing an alpha package, so any help regarding that is appreciated.

image

Alpha branch got uncaught error, not able to test the next features. Check it out in the codesandbox, https://codesandbox.io/s/morning-rgb-sfhzj?file=/src/index.js

**Comment by iamhosseindhv** [comment]
You were almost there @liho00. Here's a working example: https://codesandbox.io/s/cold-brook-gsubs?file=/src/index.js

You can download the alpha package by `npm i notistack@alpha`.

**Comment by liho00** [comment]
> You were almost there @liho00. Here's a working example: https://codesandbox.io/s/cold-brook-gsubs?file=/src/index.js
> 
> You can download the alpha package by `npm i notistack@alpha`.

We must use the forwardRef in order to use this new feature? Is there any other ways to achieve this new feature without using forwardRef? Or can we encapsulate forwardRef in this package?

**Comment by iamhosseindhv** [comment]
@liho00 Yes you'll have to use `forwardRef`. This is needed for transition animations to work.

**Comment by emilshr** [comment]
Can custom variants be defined when using Typescript?
I tried using the `alpha` version. The variants which can be mentioned are limited to only the `VariantType`.

That is,
- success
- warning
- default
- info
- error

**Comment by iamhosseindhv** [comment]
Closing this PR as it certainly won't be merged.

Download notistack v3 using `npm i notistack@alpha` (in alpha) which gives you full control. Instead of trying to override styles, you make your own snackbars. Here's an example: https://codesandbox.io/s/pedantic-shaw-y3nis
Take a look at `ThemeResponsiveSnackbar.tsx` and change the styles as you wish.

On v3, you can define custom variants:

```tsx
<SnackbarProvider
    Components={{
        success: MyCustomSuccessNotification,
        reportComplete: ReportComplete,
    }}
>
</SnackbarProvider>

interface ReportCompleteProps extends CustomContentProps {
    allowDownload: boolean;
}

const ReportComplete = React.forwardRef((props: ReportCompleteProps, ref) => {
    const {
        // You have access to notistack props, options 👇🏼
        variant,
        message
        // as well as your own custom props 👇🏼
        allowDownload,
    } = props;

    // 
})

enqueueSnackbar('Your report is ready to download', {
   variant: 'reportComplete',
   persist: true,
   allowDownload: true, // <-- pass any additional options
})
```

**Pull request closed without merging**
