### PR TITLE
add useSnackbar hook

### PR DESCRIPTION
**Pull request by ecwyne**
Thank you for creating this project!

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
Thanks @ecwyne ❤️

**Comment by maximenathan** [comment]
:+1: 

Any news?

**Comment by ricokahler** [comment]
shameless bump

❤️ love this library and can't wait to use it with hooks!

**Comment by iamhosseindhv** [comment]
Sorry for the delay guys. Will publish new version deprecating `onPresentSnackbar` and adding support for hooks by the end of this week. ❤️

**Comment by iamhosseindhv** [comment]
Happy to say `v0.6.0` has been published and finally we support hooks.

Thanks for your patience.

**Pull request merged**
