### PR TITLE
fix: change stack.message to {...stack} for having all options passed…

### PR DESCRIPTION
**Pull request by Abolfazl2647**
in ```SnackbarProvider``` we have ```content``` props which we can pass our component for customization.
the ```content``` props have two parameters ```key``` and ```message``` but there is only one issue with this, we never actually can find out which variant we showing. 
what i do is just pass the ```snack``` itself so we can have access to all the options we passed to ```enqueueSnackbar``` when we call it.

### CODE REVIEW

**Comment by sizata-siege** [comment]
That's a great idea! It would be so nice if this PR is merged!

**Comment by Abolfazl2647** [comment]
> That's a great idea! It would be so nice if this PR is merged!
> 
> with a simple & smart change, everything would work as expected, no new version, no stuff needed to reach this goal!

Thank you @sizata-s

**Comment by Abolfazl2647** [comment]
@iamhosseindhv i am very pleased if you tell me why you close this merge request ?

**Comment by FMGordillo** [comment]
It seems like you closed it 👀 
@Abolfazl2647 
image

**Comment by Abolfazl2647** [comment]
> It seems like you closed it eyes @Abolfazl2647 image

i did not notice that.
i don't even remember when did it happened :-D.

**Comment by iamhosseindhv** [comment]
Closing in favour of v3 implementation which is in alpha downloadable by `npm i notistack@alpha`.  Read the [migration guide](https://github.com/iamhosseindhv/notistack/blob/545a05b7cf9c67ef2ee0310d3b1b93989914f0f7/MIGRATION.md#8-new-components-prop) for more info.

**Pull request closed without merging**
