### PR TITLE
Add support for Material-UI v5 beta

### LINKED ISSUE #412: Material-UI 5.0 support
## Expected Behavior
Project should be able to compile

## Current Behavior
notistack imports makeStyle and friends from @material-ui/core/styles, which doesn't seem to export these functions anymore, and thus we need to update the imports to import from @material-ui/styles instead.

## Steps to Reproduce
Upgrade an existing project to material-ui 5, or create a test project.

## Context
I'm trying to upgrade to material-ui 5.0 (it's in beta at the moment), to see if that solves some of my issues with an autocomplete form, but then it breaks functionality with notistack.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v1.0.9  |
| React        |  17.02    |
| Material-UI | 5.0.0-beta |
| etc.         |         |

### PR DESCRIPTION
**Pull request by joemaffei**
This is a refactor of the existing styling using the conventions recommended by the Material-UI team for upgrading to v5.

Fixes #412

### CODE REVIEW

**Comment by benediktdertinger** [comment]
@iamhosseindhv is there any chance this can merged the upcoming days?

**Comment by iamhosseindhv** [comment]
Thanks for your contribution. I'm reviewing this PR

**Comment by rickstaa** [comment]
@joemaffei thanks a lot for creating this pull request and @iamhosseindhv for reviewing this pull request. 

I tested out this pull request with my JS and TS Notistack test repositories (i.e., [rickstaa/notistack-test/tree/mui-v5-upgrade](https://github.com/rickstaa/notistack-test/tree/mui-v5-upgrade) and [rickstaa/notistack-ts- test/tree/mui-v5-upgrade)](https://github.com/rickstaa/notistack-test/tree/mui-v5-upgrade)), and I keep running into the following error:

```bash
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
```

This error however is already present on the [next branch](https://github.com/iamhosseindhv/notistack/tree/next) without merging this pull request. I think we need to fix this error first before merging this pull request. I created #419 to track this bug.

**Comment by rickstaa** [comment]
@joemaffei, @iamhosseindhv Seems to work fine with material-ui v5 when the `package-lock.json` file is removed and recreated.

**Comment by joemaffei** [comment]
@iamhosseindhv conflicts resolved

**Comment by iamhosseindhv** [comment]
Thanks for your contribution all specially @joemaffei @onpaws ❤️. You can now use this by `npm i notistack@next`. Please open a new issue if you're having any issues.

**Pull request merged**
