### PR TITLE
Add replaceContent function

### PR DESCRIPTION
**Pull request by matt-ehinger**
This is a PR for issue #234 
- Replace a Snack's content by passing in key and new ReactNode

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
I'm not a big fan of adding a new method `updateSnackbar`. 

People should be able to call the same old `enqueueSnackbar` and if we see there's already a snackbar with the specified `key`,  we update it's content intstead of enqueueing a new one.

**Comment by matt-ehinger** [comment]
@iamhosseindhv appreciate the feedback! I'll work on that this week

**Comment by llccrr** [comment]
Hi, do you have any updates about this PR ? @matt-ehinger 
Thank you ! :)

**Comment by ievgennaida** [comment]
Could you please finish up this with the enqueueSnackbar?

**Comment by matt-ehinger** [comment]
Hi sorry for the delay, gonna take another look at this today.

**Comment by iamhosseindhv** [comment]
Closed due to inactivity. Also `alpha` branch has major changes and this PR is very out of date.

**Comment by simplenotezy** [comment]
@iamhosseindhv Curious; does the alpha branch support updating of content? E.g. when using a state reference in the "action" parameter, the updated state does not reflect in "actions"

**Pull request closed without merging**
