### PR TITLE
Extend functionality with `createPortal` optional approach

### PR DESCRIPTION
**Pull request by PeterMK85**
Scope:
Provide functionality to be able to render into `React.createPortal`

Issue Reported:
https://github.com/iamhosseindhv/notistack/issues/178

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
Thanks @PeterMK85 💙 . Would you be able to provide a sandbox demonstrating the new feature?
 I'm happy to merge

**Comment by PeterMK85** [comment]
@iamhosseindhv 

Example sandbox:
https://codesandbox.io/s/notistack-simple-example-nqeep?fontsize=14

_Note: If you debug you can see, that the parent element of the `notistack` will be `react-notification` not the `root` as the rest of the application_

**Comment by PeterMK85** [comment]
@iamhosseindhv
Do I need to provide anything else? Thanks :bowing_man:

**Comment by iamhosseindhv** [comment]
Thanks for your contribution and patience @PeterMK85 . This didn't make it to `v0.9.6` as I need to add an example to the website, and update docs. Will be published in `v0.9.7`.

**Comment by PeterMK85** [comment]
@iamhosseindhv 
Sorry for bothering, do we have an ETA for the `v0.9.7` release?

**Pull request merged**
