### PR TITLE
Allow "onClose" and "onExited" callbacks

### PR DESCRIPTION
**Pull request by nocksapp**
As global for all snacks on the SnackbarProvider and for single snacks created with enqueueSnackbar

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
@nocksapp Could you give an example of a scenario where having access to `onClose` and `onExit` callbacks is useful.

**Comment by iamhosseindhv** [comment]
This will be merged for the next version of notistack. Thanks for the contribution @nocksapp ❤️

**Comment by iamhosseindhv** [comment]
@nocksapp Functionality has been added to master branch, and will be included in the next release. Thanks for reporting this and the PR. ❤️

**Comment by zsh1313** [comment]
I have latest version 0.4.1 installed through npm, I don't see this PR is merged.
Which version is it going to be merged to

**Comment by zsh1313** [comment]
@iamhosseindhv In commit a53a91d, the parameters in onClose callback is (event, reason, key), but in 728e004, the parameter is only (key).
The reason I prefer the changes in a53a91d is that I need to know the onClose reason, so that I can do something programmably  if reason is "timeout", otherwise do nothing. 
Also the current implementation with commit 728e004  is against the docs as it says: "All material-ui Snackbar props will get passed down to a Snackbar component" as mentioned by @nocksapp .
Anyway, is there way to know the onClose reason in my custom onClose callback func with the current implementation?

**Comment by iamhosseindhv** [comment]
I see your point @zsh1313. However, there're only two possible reasons: `timeout` and `clickaway`. notistack [returns](https://github.com/iamhosseindhv/notistack/blob/728e004357161cdb1e01173963219303dd38dbfd/src/SnackbarItem/SnackbarItem.js#L21) on `clickaway` event. 

> The reason I prefer the changes in a53a91d is that I need to know the onClose reason, so that I can do something _programmatically_ if reason is "timeout", otherwise do nothing.

so basically notistack does the `"otherwise do nothing"` part of your work, and the function you pass only gets called if the reason is timeout. 

@nocksapp was right about what he mentioned previously, as at the time there was no support for `onClose` and `onExited` props.

with the current implementation there isn't a way of accessing `reason`. 
lmk if you can think of a use case where reason is beneficial.

**Comment by zsh1313** [comment]
@iamhosseindhv 

>

**Comment by iamhosseindhv** [comment]
Fair enough @zsh1313. didn't know `reason` can be `undefined`. I based my argument on material [docs](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Snackbar/Snackbar.js#L339).

Anyhow, so line [21-23](https://github.com/iamhosseindhv/notistack/blob/728e004357161cdb1e01173963219303dd38dbfd/src/SnackbarItem/SnackbarItem.js#L22) would be?:

```javascript
if (reason === 'clickaway') return;
if (singleOnClose) singleOnClose(event, reason, key);
onClose(event, reason, key);
```

**Comment by zsh1313** [comment]
That looks good @iamhosseindhv . 
Better update the document as well so that we know there is an extra parameter (key) in callback

**Comment by iamhosseindhv** [comment]
👍🏼Appreciate if you could open a new issue for this. The fix will be published in the next version.

**Comment by zsh1313** [comment]
@iamhosseindhv Sorry for late reply. I have created a new issue about what we have discussed

**Comment by iamhosseindhv** [comment]
@zsh1313 Thanks

**Pull request closed without merging**
