### PR TITLE
[alpha] Add .bind(this) to method stored in provider state

### LINKED ISSUE #393: `this.props` undefined on the unstable release
When I use notistack alpha in material-ui v5, I get the error `Cannot read property 'props' of undefined.`

If I change the notistack version to `1.0.6`, I don't get this error.
Is there anything I can do to help?

| Tech         | Version |
|--------------|---------|
| Notistack | 2.0.1-alpha.4  |
| material-ui | 5.0.0-alpha.34 |

### PR DESCRIPTION
**Pull request by anthonyraymond**
Fix #393

### CODE REVIEW

**Review by Moshyfawn — APPROVED** [review]

**Review by stass-1 — APPROVED** [review]

**Comment by tifosiblack** [comment]
Could we merge this as it's a blocking issue

**Comment by bpred754** [comment]
Any word on this?

**Comment by emilshr** [comment]
Merging this PR will be great!
Even I am stuck with this blocking issue
👍🏽

**Comment by tifosiblack** [comment]
Meanwhile I used a workaround :
```ts
class FixedSnackbarProvider<
  V extends keyof T,
  T extends Record<V, React.ComponentType<any>>,
> extends SnackbarProvider<V, T> {
  constructor(props: SnackbarProviderProps) {
    super(props)
    const { enqueueSnackbar, closeSnackbar } = (this.state as any).contextValue

    this.state = {
      ...this.state,
      contextValue: {
        enqueueSnackbar: enqueueSnackbar.bind(this),
        closeSnackbar: closeSnackbar.bind(this),
      },
    }
  }
}
```

**Comment by emilshr** [comment]
I have used this temporary fix and it works great! 
Thanks @tifosiblack

**Comment by iamhosseindhv** [comment]
Thanks for your contribution ❤️ . You can download the fix by `npm i notistack@alpha`.

**Pull request merged**
