### PR TITLE
Add support for resizable snackbars

### LINKED ISSUE #132: On examples of documentation, on Custom Snackbar, if you open two snackbars and expend one, it will overlap the other
## Expected Behavior
When one of the snackbar is expended, the other snackbar should reposition to not overlap with the expended snackbar

## Current Behavior
When there are two expendable snackbars and one is expended, it overlaps the other

## Steps to Reproduce
Go to https://iamhosseindhv.com/notistack/demos#custom-snackbar. On custom snackbar demo, click the button to open two snackbars(you might have to click twice within short time interval to have two snackbars on the screen). 
Expend the bottom snack bar. 
You will see that the expended snackbar is overlapped with the other snackbar. 

## Context
I have a need to display two expendable snackbars on the same screen, and because of this issue, the title or content of the individual snackbar is blocked. 

## Your Environment

| Tech         | Version |
|--------------|---------|
| Notistack | v0.8.6  |
| React        | 16.8.5        |
| Browser      |   Chrome Version 74.0.3729.169 (Official Build) (64-bit)      |
| etc.         |         |

### PR DESCRIPTION
**Pull request by iamhosseindhv**
**[From #164]** by @vyushin

Fixes #132,  #141 
 
### renderVariant

To most compatibility with current notistack versions i made `renderVariant` property of SnackbarProvider that can be `default` or `wrapped`.

Example:

```javascript
<SnackbarProvider
    autoHideDuration={null}
    renderVariant="wrapped"
    anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
    dense={dense}
>
        {children}
</SnackbarProvider>
```

When `renderVariant` is `wrapped` snackbars will wrapped in container and snacks will resizible.
When `renderVariant` is `default` snackbars will works without this changes (like current version).

May be in future `renderVariant` might be deleted and notistack will has `wrapped` renderVariant by default.

notistack

### CODE REVIEW

**Comment by iamhosseindhv** [comment]
Thanks @vyushin. one of the cleanest PRs in this repo ever. ❤️
I like the idea of having a wrapper container and using CSS instead of precomputed offsets.
But having a `prop` for switching between the two approaches seemed redundant. So I've removed `renderVariant` prop and made it the default behaviour to wrap snackbars inside a container.

Also, to allow displaying snackbars with different `anchorOrigin`s simultaneously, we support can have [multiple containers](https://github.com/iamhosseindhv/notistack/pull/167/commits/1ec03a23aea6fba590ed826d55a47fecb8d604d6#diff-838b1834df3c64d04228be2796e597e2R176-R183).
I've also done some styling changes for `SnackbarContainer` as it wasn't responsive on smaller screens.

The only issue preventing this PR from being merged is sudden transitions. see blow. any help is appreciated.

notistack

**Comment by vyushin** [comment]
@iamhosseindhv Thanks for positive feedback! :)
I made new pull request #168

**Comment by iamhosseindhv** [comment]
PR is ready to be merged in my view. Nice job @vyushin 👏🏼
One final test on your side and we'll merge it into `master`.

**Comment by vyushin** [comment]
Looks good! On my side this works fine.

**Comment by iamhosseindhv** [comment]
Well done @vyushin

**Pull request merged**
